/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("VehicleObjectPageObjectPage journey");

        opaTest("Navigate to VehicleObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheVehicleListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheVehicleListGenerated.onTable().iCheckRows();
            When.onTheVehicleListGenerated.onTable().iPressRow(0);

            Then.onTheVehicleObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheVehicleObjectPageGenerated.iCheckSection({ section: "GeneratedFacet1" });
            Then.onTheVehicleObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "name" });
            Then.onTheVehicleObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "brand" });
            Then.onTheVehicleObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "model" });
            Then.onTheVehicleObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "year" });
            Then.onTheVehicleObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "color" });
            Then.onTheVehicleObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "fuelType" });
            Then.onTheVehicleObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "transmission" });
            Then.onTheVehicleObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "mileage" });
            Then.onTheVehicleObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "oldPrice" });
            Then.onTheVehicleObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "newPrice" });
            Then.onTheVehicleObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "state" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});